version: "3.9"

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: rag_backend
    ports:
      - "18000:18000"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: rag_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:18000
    depends_on:
      - backend
    restart: always
