name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t rag-backend ./backend
          docker tag rag-backend:latest ${{ secrets.ECR_BACKEND_URL }}:latest
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_BACKEND_URL }}
          docker push ${{ secrets.ECR_BACKEND_URL }}:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t rag-frontend ./frontend
          docker tag rag-frontend:latest ${{ secrets.ECR_FRONTEND_URL }}:latest
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_FRONTEND_URL }}
          docker push ${{ secrets.ECR_FRONTEND_URL }}:latest

      - name: Update ECS Service (Force New Deployment)
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_SERVICE_NAME }} \
            --force-new-deployment
